// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiDispatcherSystem.Models;

#nullable disable

namespace TaxiDispatcherSystem.Migrations
{
    [DbContext(typeof(TaxiContext))]
    [Migration("20251107100740_AddVehicleTable")]
    partial class AddVehicleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("БазовийТариф")
                        .HasColumnType("float");

                    b.Property<double>("ЦінаЗаКм")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Адреса")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Довгота")
                        .HasColumnType("float");

                    b.Property<double>("Широта")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("КлієнтId")
                        .HasColumnType("int");

                    b.Property<int>("МісцеВідправленняId")
                        .HasColumnType("int");

                    b.Property<int>("МісцеПризначенняId")
                        .HasColumnType("int");

                    b.Property<int>("ОплатаId")
                        .HasColumnType("int");

                    b.Property<int?>("ПризначенийВодійId")
                        .HasColumnType("int");

                    b.Property<string>("Статус")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ТарифId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ЧасСтворення")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("КлієнтId");

                    b.HasIndex("МісцеВідправленняId");

                    b.HasIndex("МісцеПризначенняId");

                    b.HasIndex("ОплатаId");

                    b.HasIndex("ПризначенийВодійId");

                    b.HasIndex("ТарифId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Статус")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Сума")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ім_я")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Прізвище")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Роль")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Телефон")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Колір")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Марка")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Модель")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("НомернийЗнак")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Client", b =>
                {
                    b.HasBaseType("TaxiDispatcherSystem.Models.User");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Dispatcher", b =>
                {
                    b.HasBaseType("TaxiDispatcherSystem.Models.User");

                    b.HasDiscriminator().HasValue("Dispatcher");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Driver", b =>
                {
                    b.HasBaseType("TaxiDispatcherSystem.Models.User");

                    b.Property<int?>("АвтомобільId")
                        .HasColumnType("int");

                    b.Property<bool>("Доступний")
                        .HasColumnType("bit");

                    b.Property<string>("ПоточнийСтатус")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("АвтомобільId");

                    b.HasDiscriminator().HasValue("Driver");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Order", b =>
                {
                    b.HasOne("TaxiDispatcherSystem.Models.Client", "Клієнт")
                        .WithMany()
                        .HasForeignKey("КлієнтId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiDispatcherSystem.Models.Location", "МісцеВідправлення")
                        .WithMany()
                        .HasForeignKey("МісцеВідправленняId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiDispatcherSystem.Models.Location", "МісцеПризначення")
                        .WithMany()
                        .HasForeignKey("МісцеПризначенняId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiDispatcherSystem.Models.Payment", "Оплата")
                        .WithMany()
                        .HasForeignKey("ОплатаId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiDispatcherSystem.Models.Driver", "ПризначенийВодій")
                        .WithMany()
                        .HasForeignKey("ПризначенийВодійId");

                    b.HasOne("TaxiDispatcherSystem.Models.Fare", "Тариф")
                        .WithMany()
                        .HasForeignKey("ТарифId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Клієнт");

                    b.Navigation("МісцеВідправлення");

                    b.Navigation("МісцеПризначення");

                    b.Navigation("Оплата");

                    b.Navigation("ПризначенийВодій");

                    b.Navigation("Тариф");
                });

            modelBuilder.Entity("TaxiDispatcherSystem.Models.Driver", b =>
                {
                    b.HasOne("TaxiDispatcherSystem.Models.Vehicle", "Автомобіль")
                        .WithMany()
                        .HasForeignKey("АвтомобільId");

                    b.Navigation("Автомобіль");
                });
#pragma warning restore 612, 618
        }
    }
}
